apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: live-db-secret
  namespace: jitsi-overlord
spec:
  encryptedData:
    # Kryptera med:
    # echo -n "live" | kubeseal --cert https://secret.apps.ocp.overlord.se/cert.pem --raw --name=live-db-secret --namespace=jitsi-overlord
    username: AgAsQ5IMQGkZeLWPjcfGDN9U4V5dCN+DKYhhSoQy9caoQWaj30Nvt+5xFKJSxANRownBwsosm8BOwPuRzJ8RUbcRx/75WX4hG0K+mUg68RD4QWwLlekJLBi+nNCdSwtBEtapCJesrqtsz7s6YXVQ5SK2Tn+mXOMHQegWHI3EgAjx+wGA2WOZ9yL1GeQwIijXTKEZjwSxpSce15pVelxjqTwlWAHJ8FwhXhxk5F+H2z9pf5J3NIV32LZaoyJ+N6xUIKJn6Xslf8aqCG1kb1a1h/FpgkPYfK745LMGT9UaezyGcVJGeKOR1Ry7FqDFIsFh/0pyTi3Gk0EsHKdti4J8Ceivcd2jgt++5KUgigHqTx3ruZyQ8mFPqVZsf6in/QlYxuC2ueqmEMyXWf8dx7aRwxiG99bWKPdtogVPm4vE72oB1AXGaWo65Ng5WH1TPThFvWrAYyZA+VhyA1XiSKUUEMiOcM1LXKgxxROppGKqFiKmzsIau/oEYnER+uobu2vOhYL69546z0UIuxNKxImhUfuyduKhv9Ekwk6D7f5o3vIWx+1oOMls2Wo8+F2dhRtVaqtC1zhNoxuVwX1sDHOVCzN15eCAYLA2Z01RPQUyYLto1qn1vCnIq3NwuHFpD4MaQl1ggZmQ+WhMHB7zkxwoBZnCLDeeY4VqHd2i9u50+8UVwa210piXh2o1ZHv42JOnsSiUfrle
    # echo -n "<password>" | kubeseal --cert https://secret.apps.ocp.overlord.se/cert.pem --raw --name=live-db-secret --namespace=jitsi-overlord
    password: AgBfNcJP4k5eOXbFtbxAHYYGpDmBb+zhk3hIYNtJ43OUbku436a9RH91Xkzz0eZRcLS6ZkYFFP+B+rGbY3eMG+EHj/hZJHDhtYd1KrcPyw/7QwEL6ZIcOPwnTQ3kVA1lQu4nQpUORoGvh274PDfgpvI2kG6IAtXpjw0tOzb7ML6X1rL6y5VVYKtl27232c93+ggJSiUqz1Quc9+m3dP3mKapStBpo8eJg2DPPCwjm8J3EjBGR0iQ40cHdR4HUNhfU3IdYlbbM9pvQZKBh1v26L7nA769N1xQT4f7Vx8YBY0skSgszJbu4Nf7vXf7LtGQeo8AVMIqJr35GyjusB1UQeg9rifUslh/pDFJ99nRM+rYB+CtQDyCNmI7qzhs7qz3oUHFZTxPboa4boMQUGN341VdhbtarUDZtzg7xVb3IeBF1HKh7pon8rfUCtmkTLkcNi1jRN8r+Z32W8owICtcLZf6eRzEkspAcDPPbnVVvdf9vrKJTJQmgn9atrUTnBfxejJU4K04vzfnXC1DPu+T1U3MRIsW6YjsG4XxEOIKTP33W+tSvP2RXPcmVTEXtkwYDxg6qUT44uEPbPH7n2pp5nVCwMvgKhRGAv/BZ33LEOnQnsGfotH7x8wuhrG00H3Ho1CfzBzSIxHcRSob97vaqDQ3ZDjcFJdwTL5N0s4h4uyXRLItoPRD1A5SgKubXIlywJgzqViWCNYHwSl18EmrS/IDCb5caj/cBEqMTp+TP6LE
  template:
    metadata:
      name: live-db-secret
      namespace: jitsi-overlord
    type: Opaque
