apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: live-postgresql
  namespace: jitsi-overlord
spec:
  description: "Streaming platform database"
  imageName: image-registry.overlord.se/mirror/postgresql:17.6-system-trixie
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: live
      owner: live
      secret:
        name: live-db-secret
